#!/bin/sh

# Fix CapsLock key behavior
if command -v xmodmap >/dev/null; then
	if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/X11/xmodmap ]; then
		xmodmap "${XDG_CONFIG_HOME:-$HOME/.config}"/X11/xmodmap &
	else
		xmodmap -e 'clear lock' -e 'keycode 66 = Escape Caps_Lock NoSymbol NoSymbol' &
	fi
elif command -v setxkbmap >/dev/null; then
	setxkbmap -option "caps:escape_shifted_capslock" &
fi

# Set keyboard repeat rate
if command -v xset >/dev/null; then
	xset r rate 500 30
fi

# Load XResources
if command -v xrdb >/dev/null && [ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/X11/xresources ]; then
	xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}"/X11/xresources &
fi

# Disable touchscreen
if [ -f "${HOME}"/scripts/touchscreen ]; then
	sh "${HOME}"/scripts/touchscreen -d &
fi

# Start Desktop Session
if command -v cinnamon-session >/dev/null; then
	exec cinnamon-session
elif command -v startxfce4 >/dev/null; then
	exec startxfce4
fi
